sudo: required
dist: xenial

language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5


 env:
    global:
 -    - GCC_VERSION="4.9"

before_install:
    - sudo apt-get update --fix-missing
    - sudo apt-get install -qq
        libfreetype6-dev
        libx11-dev
        libstdc++6
        libxinerama-dev
        libxrandr-dev
        libxcursor-dev
        libxcomposite-dev
        mesa-common-dev
        libasound2-dev
        freeglut3-dev
        libcurl4-gnutls-dev+
        libasound2-dev
        libjack-dev
        libcsound64-6.0

    - sudo apt-get update --fix-missing
    - sudo apt-get update -qq


branches:
    only:
        - master

before_script: cd Builds/LinuxMakefile/
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - make -f MakeCabbageIDE

