sudo: required
dist: xenial

language: cpp

git:
    depth: 1

before_install:
    - sudo add-apt-repository ppa:quadrispro/ppa
    - sudo apt-get update --fix-missing
    - sudo apt-get update -qq
    - sudo apt-get install -y
        libfreetype6-dev
        libx11-dev
        libstdc++6
        libc++-dev
        libxinerama-dev
        libxrandr-dev
        libxcursor-dev
        libxcomposite-dev
        mesa-common-dev
        libasound2-dev
        freeglut3-dev
        libcurl4-gnutls-dev+
        libasound2-dev
        libjack-dev
        csound
        libcsound64-6.0
        libcsound64-dev        
        libcsnd-dev

    - sudo apt-get update --fix-missing
    

compiler:
    - gcc

branches:
    only:
        - master

before_script: 
    - cd Builds/LinuxMakefile/
    - ls /usr/local/include
script:
    - csound
    - make -f MakeCabbageIDE

