os: osx

osx_image: xcode9.2
compiler: clang
#env: CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran' BUILD_TYPE='Debug'

before_script: 
    - git clone https://github.com/WeAreROLI/JUCE.git
    - cd JUCE/extras/Projucer/Builds/MacOSX/
    - xcodebuild -project Projucer.xcodeproj
    - pwd
    - cd /users/travis/build/rorywalsh/
    - curl -o csound6.09.1-OSX-universal.dmg 'https://github.com/csound/csound/releases/download/6.09.1/csound6.09.1-OSX-universal.dmg'
    - ls
    - hdiutil attach csound6.09.1-OSX-universal.dmg
    - cp -R /Volumes/Csound6.09.1/ Csound
    - hdiutil detach csound6.09.1-OSX-universal.dmg
    - cd Csound
    - sudo installer -pkg csound6.09.1-OSX-universal.pkg -target /
    - ls /Library/Frameworks/
    - cd /users/travis/build/rorywalsh/cabbage/Builds/MacOSX

script:
  - pwd
  - sudo chmod 777 buildCabbage
  - ls
  - ../../../JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer --resave ../../CabbageIDE.jucer