os: osx

osx_image: xcode9.2
compiler: clang
#env: CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran' BUILD_TYPE='Debug'

before_script: 
    - brew install wget
    - git clone https://github.com/WeAreROLI/JUCE.git
    - cd JUCE/extras/Projucer/Builds/MacOSX/
    - xcodebuild -project Projucer.xcodeproj
    - ls
    - cd Debug
    - pwd
    - cd /Users/travis/build/rorywalsh/
    - wget 'https://github.com/csound/csound/releases/download/6.09.1/csound6.09.1-OSX-universal.dmg'
    - ls
    - hdiutil attach csound6.09.1-OSX-universal.dmg
    - cp -R /Volumes/Csound6.09.1/ Csound
    - hdiutil detach /Volumes/Csound6.09.1/
    - cd Csound
    - sudo installer -pkg csound6.09.1-OSX-universal.pkg -target /
    - ls /Library/Frameworks/
    - cd /Users/travis/build/rorywalsh/
    - wget 'https://download.steinberg.net/sdk_downloads/vstsdk368_08_11_2017_build_121.zip'
    - unzip -a vstsdk368_08_11_2017_build_121.zip
    - mkdir ~/SDKs
    - cp -rf VST_SDK ~/SDKs
    - cd /Users/travis/build/rorywalsh/cabbage/Builds/MacOSX

script:
    - /Users/travis/build/rorywalsh/cabbage/JUCE/extras/Projucer/Builds/MacOSXDebug/Projucer --resave ../../CabbageIDE.jucer
    - xcodebuild -project Cabbage.xcodeproj clean
    - xcodebuild -project Cabbage.xcodeproj/ ARCHS="i386 x86_64" ONLY_ACTIVE_ARCH=NO -configuration Release

    - /Users/travis/build/rorywalsh/cabbage/JUCE/extras/Projucer/Builds/MacOSX/Debug/Projucer--resave ../../CabbageLite.jucer
    - xcodebuild -project CabbageLite.xcodeproj clean
    - xcodebuild -project CabbageLite.xcodeproj/ ARCHS="i386 x86_64" ONLY_ACTIVE_ARCH=NO -configuration Release
    
    - /Users/travis/build/rorywalsh/cabbage/JUCE/extras/Projucer/Builds/MacOSXDebug/Projucer --resave ../../CabbagePlugin.jucer
    - xcodebuild -project CabbagePlugin.xcodeproj/ ARCHS="i386 x86_64" ONLY_ACTIVE_ARCH=NO -configuration Release GCC_PREPROCESSOR_DEFINITIONS="Cabbage_Plugin_Synth=1 USE_DOUBLE=1 CSOUND6=1 MACOSX=1"
    - cp -rf ./build/Release/CabbagePlugin.vst/ ./build/Release/Cabbage.app/Contents/CabbagePluginSynth.vst
    - cp -rf ./build/Release/CabbagePlugin.vst/ ./build/Release/CabbageLite.app/Contents/CabbagePluginSynth.vst

    - xcodebuild -project CabbagePlugin.xcodeproj/ -configuration Release ARCHS="i386 x86_64" ONLY_ACTIVE_ARCH=NO GCC_PREPROCESSOR_DEFINITIONS="MACOSX=1 USE_DOUBLE=1"
    - cp -rf ./build/Release/CabbagePlugin.vst/ ./build/Release/Cabbage.app/Contents/CabbagePluginEffect.vst
    - cp -rf ./build/Release/CabbagePlugin.vst/ ./build/Release/CabbageLite.app/Contents/CabbagePluginEffect.vst
    - rm -rf ./build/Release/CabbagePluginEffect.vst
    - rm -rf ~/Library/Audio/Plug-Ins/VST/CabbagePlugin.vst

    - cp -rf ../../Examples ./build/Release/Cabbage.app/Contents/Examples
    - cp -rf ../../Examples ./build/Release/CabbageLite.app/Contents/Examples