os: osx
osx_image: xcode9.2
compiler: clang
before_script:
- ls
- gem install xcpretty
- gem install xcpretty-travis-formatter
- pwd
- cd ..
- curl -L -o csound6.09.1-OSX-universal.dmg 'https://github.com/csound/csound/releases/download/6.09.1/csound6.09.1-OSX-universal.dmg'
- ls
- hdiutil attach csound6.09.1-OSX-universal.dmg
- cp -R /Volumes/Csound6.09.1/ Csound
- hdiutil detach /Volumes/Csound6.09.1/
- cd Csound
- sudo installer -pkg csound6.09.1-OSX-universal.pkg -target /
- cd /Users/travis/build/rorywalsh/
- git clone https://github.com/WeAreROLI/JUCE.git
- cd JUCE/extras/Projucer/Builds/MacOSX/
- xcodebuild -project Projucer.xcodeproj | xcpretty -f `xcpretty-travis-formatter` > /dev/null
- cd /Users/travis/build/rorywalsh/
- ls /Library/Frameworks/
- pwd
- cd /Users/travis/build/
- curl -L -o vstsdk368_08_11_2017_build_121.zip https://download.steinberg.net/sdk_downloads/vstsdk368_08_11_2017_build_121.zip
- unzip -q vstsdk368_08_11_2017_build_121.zip
- mkdir ~/SDKs
- cp -rf VST_SDK ~/SDKs
- ls /Users/travis/build/rorywalsh/
- cd /Users/travis/build/rorywalsh/cabbage/Builds/MacOSX
script:
- echo -en "travis_fold:start:building"
- "/Users/travis/build/rorywalsh/JUCE/extras/Projucer/Builds/MacOSX/build/Debug/Projucer.app/Contents/MacOS/Projucer
  --resave ../../CabbageIDE.jucer"
- xcodebuild -project Cabbage.xcodeproj/ ARCHS="i386 x86_64" ONLY_ACTIVE_ARCH=NO -configuration
  Release | xcpretty -f `xcpretty-travis-formatter` > /dev/null
- echo -en "travis_fold:end:building"
deploy:
  skip_cleanup: true
  script: skip
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  github_token: $GITHUB_TOKEN
  file:
  - "/Users/travis/build/rorywalsh/cabbage/Builds/MacOSX/build/Release/Cabbage.app"
  on:
    all_branches: true
env:
  global:
    secure: sbJ471H2r7BdOS+73IdhOslFvIaRSVkqkAnv79jieAVI4Ntz4lYqNmqpmu0F8qu8SgySnb5W77y+gP7QO3oBVTmO08oqRZ4kNfLHH5wlexxee3PFgj2FKuEhj0aapZRa1igiEVibZ5nJQZpKWA6VlXSFqymMmtmOhuTwbOHaCXKa7H/qWtyZsmxQfCHaVJ2DbDLTtwyldrY3/VM6HTc6mi1Ina0tDJTh9Rirhy1U7uuvd1DaJtw2MQGNKgLQIsna6YMTfYwd2CjT8hGlNTcNqxPL7kBrfP+YSXlqtAGWau7Kcj3qFwgDoi8NU721SD2yuJZRcDeEJFKDbvvLYTgXLTOJ4S5bN3XMW4/AyLWvztMP5Zk9+Vf0juC/7X51DRVRF/HRH/R1WV/us1hkFaV3QUK3EjWC599EzWVsSsTCXa4WXIwHwRfqqNhUpeDPwoYS4Qq4tADv8sFuhiSl6egXFQK5s5qW13/FaUhEZk4uC1dnOEba5jgTONd9CdPEMIr4QOgrMXHkLSoNybpK6luVkFvg823kCsgwQeiuZSoqKlleKtam2bIlNfPXG1MPI64DGhQhTJuPoJrCi9KcIBuK+Ax8wmAoQHmMqBoOWaXfVtcWfNKPFdnFRljNiEiYG+DIbUigJJCofH9BogbD+CDBLdNA5eOnSfvx1rokfEsMSfs=
