sudo: required
dist: trusty

language: cpp

git:
    depth: 1

before_install:
    - sudo apt-get update --fix-missing
    - sudo apt-get update -qq
    - sudo apt-get install -y
        libfreetype6-dev
        libx11-dev
        libstdc++6
        libc++-dev
        libxinerama-dev
        libxrandr-dev
        libxcursor-dev
        libxcomposite-dev
        mesa-common-dev
        libasound2-dev
        freeglut3-dev
        libcurl4-gnutls-dev+
        libasound2-dev
        libjack-dev
        libcsound64-6.0
        libcsnd-dev

    - sudo apt-get update --fix-missing
    

compiler:
    - clang++

branches:
    only:
        - master

before_script: cd Builds/LinuxMakefile/
script:
    - ls /usr/local/include/



