os: osx

osx_image: xcode9.2
compiler: clang
#env: CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran' BUILD_TYPE='Debug'

before_script: 
    - git clone https://github.com/WeAreROLI/JUCE.git
    - cd JUCE/extras/Projucer/Builds/MacOSX/
    - xcodebuild -project Projucer.xcodeproj
    - pwd
    - cd /home/travis/build/rorywalsh/cabbage/Builds/MacOSX

script:
  - pwd
  - sudo chmod 777 buildCabbage
  - ls
  - ../../../JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer --resave ../../CabbageIDE.jucer