sudo: required
dist: trusty
language: cpp
compiler: gcc
before_script:
- ls
- gem install xcpretty
- gem install xcpretty-travis-formatter
- pwd
- git remote rm origin
- git remote add origin https://rorywalsh:${GH_TOKEN}@github.com/rorywalsh/cabbage.git
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git push --delete origin vBeta
- git tag vBeta -a -m "Generated tag for beta build"
- git push --tags
script:
- export PROJUCER=/Users/travis/build/rorywalsh/JUCE/extras/Projucer/Builds/MacOSX/build/Debug/Projucer.app/Contents/MacOS/Projucer
- echo -en "travis_fold:start:buildingIDE"
- echo -en "travis_fold:end:buildingIDE"
env:
  global:
    secure: Rutly8wQi3KfYQOf4du0QuPBbQgoYn8oMJUe51mpilcAX8kfmi98jocycek1wrkTOlZAZMJvA1GHC/Z6CN05NtnjrJGOW+9u6dEv/0Wrz2yYOBVZYZrvTyVoGJhs7Xy3mJ9IufihhDmfkWEIWb3uDEDBVz9QLGOg9JkK6090iGJZPq7oFY0xlJcxzpcbFOyYH2OfArJLVnrHWvfTzMv+zk5LXi70V2MeuHrKqK1uHt40GoxHhOdJGSkcm+l8zufA1o6I2RM21Shu/5s0is7PR7rUJzy9s5X4z9q/xKN3K0FLa/kmzOR5j2RYJWQdnnfe5HX6lkijot8FZQJl8oExQay/4og2gHf9UyJRr6/a2YLy25mCF7J9Va8ffxxHOiAP3jGu5QFjzWxuKxi6wQT5/XIvGbrx1whZ7b89Dmu2JTo0lHQQuiMHwqg19w37HH9t4YC1yKbiqmJLunJSekd96nRef4fqOxRiOgce2BX+fLM+UehEP+uZ3qFRdCJ8q6qVQv8bloGhmzv6h2GKvur1yqF584KETtkHd+0Ex9OhF+FwHUsbjHZeTfsMCbKOyawdx6oXN1mESfW/SdJYC0SFrDX6BI0R53aYLeEaOpqerP5I+E/cz2XAiwzM+v6kgNe//5dxmAkFCAedoBzscfbbzORJcGkR9Nhys9jJOD3cjiM=
