sudo: false
language: cpp

os: osx
osx_image: xcode9.2

install:
 sudo cp -R /Volumes/Csound6.09.1/ ./testOutput/
    filename="$*"
    dirname="${filename/\./_}"
    pkgutil --expand "$filename" "$dirname"
    cd "$dirname"
    tar xvf Payload
    open .
    
script:
  - mvn dependency:get -Dartifact=junit:junit:4.8.2 -DrepoUrl=http://repo1.maven.org/maven2/
- ant -Dnbplatform.default.harness.dir=$PWD/netbeans/harness -Dnbplatform.default.netbeans.dest.dir=$PWD/netbeans -DfopCommand=fop test build-mac

    
    
    
