language: cpp

os:
  - linux
  - osx

osx_image: xcode9.2

compiler:
  - gcc
  - clang

install:
  - '[ "${TRAVIS_OS_NAME}" = "osx" ] && brew update || true'
  - '[ "${TRAVIS_OS_NAME}" = "osx" ] && brew install ant fop || true'

script:
  - pwd