sudo: required
dist: trusty

language: cpp
compiler: gcc

git:
    depth: 10

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "OsiLt01SfvDANKBXykWTunHJUdMqVXlEmKDhiw5LRYJvlZ8zVDL43xhtJQ31uPTLrXNxJ76bHJ755MO5WiLjGcFCHYb7uCWkbHk6w+TUn6pnnZPVL7eBSZ52QGeKD9SUv7xGTzge9bB2n6VlfIBAl1Po1U1erGFuJ9KAMi4G39bqUmwI4l596MGroZdJnEpsO+JU+4sygmrSReZFmQ7hqMOJ2/xcB5BIyL6xJBJigVnaTrgnSYYtP6N0YMdLumcpK0svHxczqgvn+vhpy13zdzfWGkYI7NY7pKD3tfV/dkKJsQoOAnFR93UA7kNSMaxlLFuMtyi+mHfOG96A5J2n9sssuJ92SXNcehs5yuXD/qy6904sfxgbXgAyNkopEGJ44b2bz7zWDKmmD7M62C/YWWwZHQC4y23wWVNbseS/eut/cS8yr1+fhurdveWdrv4Y3X1e0ZZbMrcxbRuJUYClXBNoYQF1jT0pwxOoMRahF25u+oE2y4ftVzDIdAKond3Fum7KrQ+rZqnF/gk9+nnIQBZdk0XldCeZsDuE1ZOfoKv9hpXE5kGtq6h9hfGxxUUVBmQHgh+BQCA2D/T6khoDODHJcoPa4lrThDLkcU8IxTlcmR/MqohUBrQEljRZEroPrBsLYELuhXopgSaL65Li+PrxYtpyp2lrnx3//QdOWZs="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
  coverity_scan:
    project:
      name: "rorywalsh/cabbage"
      description: "<Your project description here>"
    notification_email: rorywalsh@ear.ie
    build_command_prepend: 

    build_command:  "make -f ~/build/rorywalsh/cabbage/Builds/LinuxMakefile/MakeCabbageIDE"
    branch_pattern: coverity_scan

before_install:
    - sudo apt-get build-dep csound
    - sudo apt-get update --fix-missing
    - sudo apt-get update -qq
    - sudo apt-get install -y
        libfreetype6-dev
        libx11-dev
        libstdc++6
        libc++-dev
        libxinerama-dev
        libxrandr-dev
        libxcursor-dev
        libxcomposite-dev
        mesa-common-dev
        libasound2-dev
        freeglut3-dev
        libcurl4-gnutls-dev+
        libasound2-dev
        libsndfile1
        libjack-dev
    - sudo add-apt-repository -y ppa:webkit-team/ppa
    - sudo apt-get update
    - sudo apt-get install libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
    - sudo apt-get update --fix-missing
    

compiler:
    - gcc

before_script: 
    - cd ..
    - sudo apt-get install libsndfile1
    - mkdir csoundMaster
    - cd csoundMaster
    - git clone https://github.com/csound/csound.git
    - cd csound
    - mkdir build
    - cd build
    - cmake .. -DUSE_GETTEXT=0 -DBUILD_CSOUNDVST=0 -DBUILD_PD_CLASS=0 -DBUILD_STATIC_LIBRARY=1 -DBUILD_VST4CS_OPCODES=0 -DBUILD_VST4CS_OPCODES=0 -DBUILD_CSOUND_AC_LUA_INTERFACE=0 -DBUILD_LUA_OPCODES:BOOL=0 -DBUILD_CSOUND_AC=0 -DBUILD_CSOUND_AC_LUA_INTERFACE=0 -DBUILD_CSOUND_AC_PYTHON_INTERFAC=0 
    - sudo make -j4
    - sudo make install
    - sudo ldconfig
    - cd /home/travis/build/rorywalsh/cabbage/Builds/LinuxMakefile/

script:
    - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
    - gcc -v && g++ -v && cmake --version
    - make -f MakeCabbageIDE -j6
    - make -f MakePluginEffect clean
    - make -f MakePluginEffect -j6
    - make -f MakePluginSynth clean
    - make -f MakePluginSynth -j6
    
    
    
