os: osx

language: cpp

osx_image: xcode9.2

    compiler: clang
    env: CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran' BUILD_TYPE='Debug'

install:
  - '[ "${TRAVIS_OS_NAME}" = "osx" ] && brew update || true'
  - '[ "${TRAVIS_OS_NAME}" = "osx" ] && brew install ant fop || true'

script:
  - pwd