image: Visual Studio 2017

version: configuring.{build}
configuration:
- Debug

environment:
  VSTOOLSET: v141


platform:
- x64


clone_folder: c:\cabbage

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - echo This is batch
  - cmd: cd c:/
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/buildjobs/u7oafdbd9rbntueh/artifacts/csound-windows-x64-6.10.0-rc2-1060.zip'
  - cmd: 7z.exe x csound-windows-x64-6.10.0-rc2-1060.zip -o Csound6_x64
  - cmd: xcopy Csound6_x64 "C:/Program Files/Csound6_x64" /O /X /E /H /K
  - cmd: cd "C:/Program Files/Csound6_x64"
  - cmd: dir
  - cmd: cd c:/
  - cmd: git clone https://github.com/WeAreROLI/JUCE.git
  - cmd: cd JUCE/extras/Projucer/JuceLibraryCode
  - ps: (Get-Content -Path "AppConfig.h") | ForEach-Object {$_ -Replace "#define JUCER_ENABLE_GPL_MODE 1", "#define JUCER_ENABLE_GPL_MODE 0"} | Set-Content -Path "AppConfig.h"
  - ps: (Get-Content -Path "AppConfig.h") | ForEach-Object {$_ -Replace "#define JUCE_USE_DARK_SPLASH_SCREEN 1", "#define JUCE_USE_DARK_SPLASH_SCREEN 0"} | Set-Content -Path "AppConfig.h"
  - cmd: cd ../Builds/VisualStudio2017/
  - cmd: msbuild Projucer.sln /property:Platform=x64
  